name: book_store
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  flutter_spinkit: ^5.1.0
  get: ^4.6.5
  hive: ^2.2.3
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  mocktail: ^0.3.0
  path_provider: ^2.0.11
  url_launcher: ^6.1.6


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/book_store_icon.png"
  min_sdk_android: 21 

flutter:
  assets:
    - assets/
  uses-material-design: true

